# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Minimize js file CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - uses: actions/checkout@v3.2.0
        with:
          ref: ${{ github.head_ref }}
          
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1.1
        with:
          overwrite: false
          output: 'mini_js'

      # Auto commits minified content to the existing files
      # Ignore it if you don't want to commit the files to the repository 
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          
